name: Better Wolves
main: wolves.BetterWolves
version: 1.0
commands:
    sit:
        description: Makes all of your tamed wolves sit.
        usage: /<command>
    stand:
        description: Makes all of your tamed wolves stand.
        usage: /<command>
    wolves:
        description: Counts the number of wolves in your possession.
        usage: /<command>
    safestand:
        description: Makes all but two of your wolves stand.
        usage: /<command>
    wolfcolor:
        description: Allows a player to claim a collar color for their wolves.
        usage: /<command> <color>
    wolfrefresh:
        description: Refreshes all of the wolves' collars.
        usage: /<command>
    allcolors:
        description: Lists all of the colors claimed.
        usage: /<command>
    jointeam:
        description: Allows a player to join the specified team.
        usage: /<command> <team name>
    getteam:
        description: Gets what team you are on.
        usage: /<command>
    allteams:
        description: Shows all players and their current team.
        usage: /<command>